                                                                                                                                                                                   
var lista = [
{ nome : "LEONARDO SZCZEPANIAK",        equipe : "ENGECAR" },
{ nome : "ANDERSON HOFFMEISTER",        equipe : "VELOPARK" },
{ nome : "DIEGO ARAUJO",                equipe : "METALMORO" },
{ nome : "ANDERSON PELLIN",             equipe : "INJEPRO" },
{ nome : "DIEGO ARAUJO",                equipe : "STYLLO CAFÉ" },
{ nome : "ANDERSON PELLIN",        equipe : "LOPES PETRÓPOLIS" },
{ nome : "DIEGO ARAUJO",                equipe : "CARBONI SUPERMERCADOS" },
{ nome : "ANDERSON PELLIN",        equipe : "ADESCA" },
{ nome : "DIEGO ARAUJO",                equipe : "TRANSMAQ" },
{ nome : "ANDERSON PELLIN",        equipe : "MGTIRES" },
{ nome : "DIEGO ARAUJO",        equipe : "SERRANA" },
{ nome : "ANDERSON PELLIN",        equipe : "AUTOTECH" },
{ nome : "DIEGO ARAUJO",        equipe : "ZANOELLO " },
{ nome : "ANDERSON PELLIN",        equipe : "PATETAS RACING TEAM" },
{ nome : "DIEGO ARAUJO",        equipe : "CARBONI SUPERMERCADOS" },
{ nome : "ANDERSON PELLIN",        equipe : "CARBONI SUPERMERCADOS" },
{ nome : "DIEGO ARAUJO",        equipe : "CARBONI SUPERMERCADOS" },
{ nome : "ANDERSON PELLIN",        equipe : "CARBONI SUPERMERCADOS" },
{ nome : "DIEGO ARAUJO",        equipe : "PATETAS RACING TEAM" },
{ nome : "ANDERSON PELLIN",        equipe : "PATETAS RACING TEAM" },
{ nome : "DIEGO ARAUJO",        equipe : "PATETAS RACING TEAM" },
{ nome : "ANDERSON PELLIN",        equipe : "PATETAS RACING TEAM" },
{ nome : "DIEGO ARAUJO",        equipe : "VELOPARK" },
{ nome : "ANDERSON PELLIN",        equipe : "VELOPARK" },
{ nome : "DIEGO ARAUJO",        equipe : "VELOPARK" },
{ nome : "ANDERSON PELLIN",        equipe : "VELOPARK" },
{ nome : "DIEGO ARAUJO",        equipe : "VELOPARK" },
{ nome : "ANDERSON PELLIN",        equipe : "VELOPARK" },
{ nome : "DIEGO ARAUJO",        equipe : "VELOPARK" },
{ nome : "ANDERSON PELLIN",        equipe : "VELOPARK" }
];

