<?php
class ParametroEmun {
	const CAMPEONATO_PRINCIPAL = "CAMPEONATO_PRINCIPAL";
	const GLEVEIDADE = "GLEVEIDADE";
	const GLEVEPESO = "GLEVEPESO";
	const GLEVEPESOOPCIONAL = "GLEVEPESOOPCIONAL";
	const GMEDIOIDADE = "GMEDIOIDADE";
	const GMEDIOPESO = "GMEDIOPESO";
	const GMEDIOPESOOPCIONAL = "GMEDIOPESOOPCIONAL";
	const GPESADOIDADE = "GPESADOIDADE";
	const GPESADOPESO = "GPESADOPESO";
	const GPESADOPESOOPCIONAL = "GPESADOPESOOPCIONAL";
	const VLCAMP2016 = "VLCAMP2016";
	
	// INSCRI��O
	// Pago
	const INSCRICAO_SITUACAO_PG = "INSCRICAO_SITUACAO_PG";
	// Aguardando pagamento
	const INSCRICAO_SITUACAO_AP = "INSCRICAO_SITUACAO_AP";
	// Fila de espera
	const INSCRICAO_SITUACAO_LE = "INSCRICAO_SITUACAO_LE";
	// Aguardar data de pagamento
	const INSCRICAO_SITUACAO_AL = "INSCRICAO_SITUACAO_AL";
	const INSCRICAO_MSG_SUCESSO = "INSCRICAO_MSG_SUCESSO";
	const INSCRICAO_MSG_ATUALIZADO_SUCESSO = "INSCRICAO_MSG_ATUALIZADO_SUCESSO";
	const INSCRICAO_MSG_LISTA_ESPERA = "INSCRICAO_MSG_LISTA_ESPERA";
	const INSCRICAO_MSG_AGUARDANDO_PILOTOS = "INSCRICAO_MSG_AGUARDANDO_PILOTOS";
	const INSCRICAO_MSG_AGUARDANDO_PAGAMENTO = "INSCRICAO_MSG_AGUARDANDO_PAGAMENTO";
	const INSCRICAO_MSG_SUCESSO_EQUIPE = "INSCRICAO_MSG_SUCESSO_EQUIPE";
	
	// INSCRITO
	const ADICIONAR_CENTAVOS = "_ADICIONAR_CENTAVOS";
	
	
}
?>